---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api.157.230.192.106.sslip.io
      http:
        paths:
          # any request that comes in to path /, goes to the backend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bggapp-svc
                port:
                  name: bggapp-svc-port