---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-vol
  namespace: default
data:
  index.html: |
      <h1>hello world</h1>
      <h2>this is my deployment</h2>
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-vol
  namespace: default
type: Opaque
data:
  INSTANCE_NAME: c2VjcmV0cy1leGFtcGxlMg==