---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    name: myns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-example
  namespace: myns
data:
  PORT: "5000"
  INSTANCE_HASH: 3457ab49ca7b562233bee4ee4cc6cf19
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-example
  namespace: myns
type: Opaque
data:
  INSTANCE_NAME: c2VjcmV0cy1leGFtcGxlMg==